echo "begin of file"
python3 genetic-algorithm11.py >> instances/result_11.txt
python3 genetic-algorithm17.py >> instances/result_17.txt
python3 genetic-algorithm05.py >> instances/result_05.txt
python3 genetic-algorithm06.py >> instances/result_06.txt
python3 genetic-algorithm09.py >> instances/result_09.txt
python3 genetic-algorithm10.py >> instances/result_10.txt
python3 genetic-algorithm12.py >> instances/result_12.txt
python3 genetic-algorithm15.py >> instances/result_15.txt
python3 genetic-algorithm16.py >> instances/result_16.txt
python3 genetic-algorithm19.py >> instances/result_19.txt
python3 genetic-algorithm20.py >> instances/result_20.txt
echo "end of file"
